title:            我真的是哔了狗
description:      我真的是哔了狗的博客，有什么好看的
url:              # Site url.

highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
# Use the following plug-ins
timezone: Asia/Shanghai

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME