// Generated by CoffeeScript 1.6.3
jQuery(function() {
  return $.each($("[data-time]"), function(index, ele) {
      console.log($(this).data("format"))
    return $(ele).html($(this).data("format")==true?new Date($(this).data("time")).format("yyyy年MM月dd日"):prettyDate(new Date($(this).data("time"))));
  });
});
